import type { RoleKey } from "../memberships/membership";

export const PERMISSIONS = {
  CLIENT_CREATE: "PERM.CLIENT.CREATE",
  CLIENT_VIEW: "PERM.CLIENT.VIEW",
  CLIENT_VIEW_ALL_IN_TENANT: "PERM.CLIENT.VIEW_ALL_IN_TENANT",
  CONTRACT_CREATE: "PERM.CONTRACT.CREATE",
  CONTRACT_VIEW: "PERM.CONTRACT.VIEW",
  PACKAGE_CREATE: "PERM.PACKAGE.CREATE",
  PACKAGE_ADJUST: "PERM.PACKAGE.ADJUST",
  DELIVERABLE_CREATE: "PERM.DELIVERABLE.CREATE",
  DELIVERABLE_EXTRA_CREATE: "PERM.DELIVERABLE.EXTRA_CREATE",
  DELIVERABLE_CANCEL_NOT_STARTED: "PERM.DELIVERABLE.CANCEL_NOT_STARTED",
  LEDGER_VIEW_SUMMARY: "PERM.LEDGER.VIEW_SUMMARY",
  USER_VIEW: "PERM.USR.VIEW",
  USER_INVITE: "PERM.USR.INVITE",
  USER_INVITE_RESEND: "PERM.USR.INVITE_RESEND",
  USER_ROLE_UPDATE: "PERM.USR.ROLE_UPDATE",
  USER_SUSPEND: "PERM.USR.SUSPEND",
  USER_RESPONSIBILITY_TRANSFER: "PERM.USR.RESPONSIBILITY_TRANSFER",
  AUDIT_USER_VIEW: "PERM.AUDIT.USER_VIEW",
  AUDIT_CLIENT_VIEW: "PERM.AUDIT.CLIENT_VIEW",
} as const;

export type PermissionId = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const rolePermissions: Record<RoleKey, readonly PermissionId[]> = {
  tenant_owner: Object.values(PERMISSIONS),
  tenant_administrator: Object.values(PERMISSIONS),
  account_manager: [
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.DELIVERABLE_CREATE,
    PERMISSIONS.DELIVERABLE_CANCEL_NOT_STARTED,
    PERMISSIONS.LEDGER_VIEW_SUMMARY,
  ],
  content_writer: [PERMISSIONS.CLIENT_VIEW],
  designer: [PERMISSIONS.CLIENT_VIEW],
  client_admin: [
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.LEDGER_VIEW_SUMMARY,
  ],
  client_approver: [
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.LEDGER_VIEW_SUMMARY,
  ],
  client_viewer: [
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.LEDGER_VIEW_SUMMARY,
  ],
};

export const roleGrantsPermission = (
  roleKey: RoleKey,
  permission: PermissionId,
) => rolePermissions[roleKey].includes(permission);
